// export enum TYPES {
//     AUTH_ACTION = "AUTH_ACTION",
//     ALERT_ACTION = "ALERT_ACTION",
//     THEME_ACTION = "THEME_ACTION"
// }

export const TYPES = {
    AUTH_ACTION: "AUTH_ACTION",
    ALERT_ACTION: "ALERT_ACTION",
    THEME_ACTION: "THEME_ACTION"
}